get users route
agile-dev-assignments/project-setup-team-hatsukaichi-dynamic pull request #206
Opened 2021-04-01 00:00 UTC by Gkal2000

I added the changes i made from my previous branch. I'm unsure why the branch can't merge.

2021-04-01 01:02 UTC, sam-eng requested changes

2021-04-01 01:02 UTC, sam-eng commented on back-end/app.js
> +    axios.get(`https://my.api.mockaroo.com/tv_users.json?key=`)
Looks good Mason! The only thing is could you add in this after `key=`? `${process.env.MOCKAROO_KEY}` (so the axios URL looks like the others in `app.js`

2021-04-01 20:13 UTC, LevBernstein approved these changes

2021-04-02 14:31 UTC, sam-eng approved these changes

2021-04-02 15:01 UTC, merged