Connect Individual Show Page to API
agile-dev-assignments/project-setup-team-hatsukaichi-dynamic pull request #209
Opened 2021-04-02 14:13 UTC by sam-eng

draft PR for now since I'm still working on this

resolves #127

2021-04-03 17:56 UTC, sam-eng commented
Something to note: there's a bug where the current status and platform for a show won't load when the page loads. I spent... a while trying to get this fixed and couldn't get it to work, so I'm putting it into its own issue.

2021-04-04 03:06 UTC, almazhankapan commented
Looks really good, thank you! Just one small edit for the font-size

2021-04-04 03:29 UTC, almazhankapan requested changes

2021-04-04 03:29 UTC, almazhankapan commented on front-end/src/IndividualShow.css
> +}
i've written a comment about the change for the font-size, thank you!

2021-04-04 18:30 UTC, almazhankapan approved these changes

2021-04-04 18:31 UTC, almazhankapan commented
great work!

2021-04-04 19:01 UTC, merged