321 replace placeholder
agile-dev-assignments/project-setup-team-hatsukaichi-dynamic pull request #332
Opened 2021-04-28 22:46 UTC by Gkal2000

2021-04-30 18:57 UTC, almazhankapan approved these changes

2021-05-01 18:06 UTC, LevBernstein requested changes

2021-05-01 18:06 UTC, LevBernstein commented on front-end/src/components/HeaderLogo.css
> +<<<<<<< HEAD
This looks like a merge artifact; it needs to be sorted out before we can merge. I get an error whenever I view a page.

2021-05-01 18:06 UTC, LevBernstein commented on front-end/src/components/HeaderLogo.js
> +import logo from '../images/newLogo.png'
newLogo seems to be an old version of the new logo; i'd suggest sticking with logo.png

2021-05-01 18:06 UTC, LevBernstein commented on front-end/src/components/Header.js
> +import logo from '../images/newLogo.png'
newLogo seems to be an old version of the new logo; i'd suggest sticking with logo.png

2021-05-01 18:47 UTC, almazhankapan commented
@LevBernstein I believe this is an outdated pr (should be closed); I picked up the task

2021-05-01 18:47 UTC, closed without merging

2021-05-01 20:16 UTC, LevBernstein commented
@almazhankapan last standup, this was what mason had said he was working on; wasn't the task assigned to him?

2021-05-01 22:16 UTC, almazhankapan commented
@LevBernstein yup,  i previously approved the pr, but then mason suggested that i pick up the task (as i am working on images and there was an issue with pr);

2021-05-01 22:45 UTC, LevBernstein commented
got it. mason should be assigned a new task, then